# Generated by Django 3.0.8 on 2020-07-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.EmailField(max_length=60)),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
