# Generated by Django 3.0.8 on 2020-07-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0005_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
